import type { Deck } from "./types.ts";
import { SLIDE_HEIGHT, SLIDE_WIDTH } from "./types.ts";

export function sampleDeck(): Deck {
  return {
    title: "Iterate without another prompt",
    width: SLIDE_WIDTH,
    height: SLIDE_HEIGHT,
    source: "sample",
    updatedAt: new Date().toISOString(),
    slides: [
      {
        id: "slide-title",
        name: "Title",
        background: "#0f172a",
        components: [
          {
            id: "t-kicker",
            type: "text",
            name: "Kicker",
            x: 120,
            y: 280,
            width: 720,
            height: 48,
            opacity: 1,
            text: "HTML SLIDE CANVAS",
            fontSize: 22,
            fontWeight: 600,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#7dd3fc",
            textAlign: "left",
            lineHeight: 1.2,
          },
          {
            id: "t-title",
            type: "text",
            name: "Title",
            x: 120,
            y: 340,
            width: 1280,
            height: 220,
            opacity: 1,
            text: "Move the slide.\nDon't prompt it again.",
            fontSize: 84,
            fontWeight: 700,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#f8fafc",
            textAlign: "left",
            lineHeight: 1.05,
          },
          {
            id: "t-sub",
            type: "text",
            name: "Subtitle",
            x: 120,
            y: 600,
            width: 900,
            height: 80,
            opacity: 1,
            text: "A 16:9 canvas for HTML decks. Drag, type, drop images, export.",
            fontSize: 28,
            fontWeight: 400,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#94a3b8",
            textAlign: "left",
            lineHeight: 1.35,
          },
          {
            id: "c-accent",
            type: "container",
            name: "Accent bar",
            x: 120,
            y: 900,
            width: 160,
            height: 8,
            opacity: 1,
            background: "#38bdf8",
            borderRadius: 99,
          },
        ],
      },
      {
        id: "slide-problem",
        name: "The loop",
        background: "#f8fafc",
        components: [
          {
            id: "p-title",
            type: "text",
            name: "Title",
            x: 120,
            y: 80,
            width: 1000,
            height: 80,
            opacity: 1,
            text: "Adoption dies in the loop",
            fontSize: 56,
            fontWeight: 700,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#0f172a",
            textAlign: "left",
            lineHeight: 1.1,
          },
          {
            id: "p-card-1",
            type: "container",
            name: "Card 1",
            x: 120,
            y: 220,
            width: 520,
            height: 700,
            opacity: 1,
            background: "#ffffff",
            borderRadius: 24,
            border: "1px solid #e2e8f0",
          },
          {
            id: "p-card-2",
            type: "container",
            name: "Card 2",
            x: 680,
            y: 220,
            width: 520,
            height: 700,
            opacity: 1,
            background: "#ffffff",
            borderRadius: 24,
            border: "1px solid #e2e8f0",
          },
          {
            id: "p-card-3",
            type: "container",
            name: "Card 3",
            x: 1240,
            y: 220,
            width: 560,
            height: 700,
            opacity: 1,
            background: "#0f172a",
            borderRadius: 24,
          },
          {
            id: "p-h1",
            type: "text",
            name: "Old way label",
            x: 160,
            y: 260,
            width: 440,
            height: 48,
            opacity: 1,
            text: "Today",
            fontSize: 22,
            fontWeight: 600,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#64748b",
            textAlign: "left",
            lineHeight: 1.2,
          },
          {
            id: "p-b1",
            type: "text",
            name: "Old way body",
            x: 160,
            y: 330,
            width: 440,
            height: 480,
            opacity: 1,
            text: "Agent writes a slide.\nYou want the title 40px left.\nYou type another prompt.\nYou wait.\nYou do it again.",
            fontSize: 28,
            fontWeight: 500,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#0f172a",
            textAlign: "left",
            lineHeight: 1.45,
          },
          {
            id: "p-h2",
            type: "text",
            name: "Canvas label",
            x: 720,
            y: 260,
            width: 440,
            height: 48,
            opacity: 1,
            text: "Canvas",
            fontSize: 22,
            fontWeight: 600,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#64748b",
            textAlign: "left",
            lineHeight: 1.2,
          },
          {
            id: "p-b2",
            type: "text",
            name: "Canvas body",
            x: 720,
            y: 330,
            width: 440,
            height: 480,
            opacity: 1,
            text: "Agent writes the first draft.\nYou drag the title.\nYou drop a photo.\nYou export HTML.\nNo second prompt.",
            fontSize: 28,
            fontWeight: 500,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#0f172a",
            textAlign: "left",
            lineHeight: 1.45,
          },
          {
            id: "p-h3",
            type: "text",
            name: "MCP label",
            x: 1280,
            y: 260,
            width: 480,
            height: 48,
            opacity: 1,
            text: "In Langdock",
            fontSize: 22,
            fontWeight: 600,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#7dd3fc",
            textAlign: "left",
            lineHeight: 1.2,
          },
          {
            id: "p-b3",
            type: "text",
            name: "MCP body",
            x: 1280,
            y: 330,
            width: 480,
            height: 480,
            opacity: 1,
            text: "show_editor opens this UI in chat.\nload_html drops a generated slide onto the board.\nYou finish the layout yourself.",
            fontSize: 28,
            fontWeight: 500,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#e2e8f0",
            textAlign: "left",
            lineHeight: 1.45,
          },
        ],
      },
      {
        id: "slide-howto",
        name: "How to use",
        background: "#ffffff",
        components: [
          {
            id: "h-title",
            type: "text",
            name: "Title",
            x: 120,
            y: 80,
            width: 1400,
            height: 90,
            opacity: 1,
            text: "First draft. Then your hands.",
            fontSize: 58,
            fontWeight: 700,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#0f172a",
            textAlign: "left",
            lineHeight: 1.1,
          },
          {
            id: "h-box-1",
            type: "container",
            name: "Step 1",
            x: 120,
            y: 240,
            width: 540,
            height: 640,
            opacity: 1,
            background: "#f1f5f9",
            borderRadius: 20,
          },
          {
            id: "h-box-2",
            type: "container",
            name: "Step 2",
            x: 690,
            y: 240,
            width: 540,
            height: 640,
            opacity: 1,
            background: "#f1f5f9",
            borderRadius: 20,
          },
          {
            id: "h-box-3",
            type: "container",
            name: "Step 3",
            x: 1260,
            y: 240,
            width: 540,
            height: 640,
            opacity: 1,
            background: "#0f172a",
            borderRadius: 20,
          },
          {
            id: "h-n1",
            type: "text",
            name: "1",
            x: 160,
            y: 280,
            width: 80,
            height: 64,
            opacity: 1,
            text: "01",
            fontSize: 32,
            fontWeight: 700,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#0284c7",
            textAlign: "left",
            lineHeight: 1,
          },
          {
            id: "h-n2",
            type: "text",
            name: "2",
            x: 730,
            y: 280,
            width: 80,
            height: 64,
            opacity: 1,
            text: "02",
            fontSize: 32,
            fontWeight: 700,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#0284c7",
            textAlign: "left",
            lineHeight: 1,
          },
          {
            id: "h-n3",
            type: "text",
            name: "3",
            x: 1300,
            y: 280,
            width: 80,
            height: 64,
            opacity: 1,
            text: "03",
            fontSize: 32,
            fontWeight: 700,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#7dd3fc",
            textAlign: "left",
            lineHeight: 1,
          },
          {
            id: "h-t1",
            type: "text",
            name: "Step 1 title",
            x: 160,
            y: 360,
            width: 460,
            height: 80,
            opacity: 1,
            text: "Insert",
            fontSize: 40,
            fontWeight: 700,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#0f172a",
            textAlign: "left",
            lineHeight: 1.1,
          },
          {
            id: "h-t2",
            type: "text",
            name: "Step 2 title",
            x: 730,
            y: 360,
            width: 460,
            height: 80,
            opacity: 1,
            text: "Arrange",
            fontSize: 40,
            fontWeight: 700,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#0f172a",
            textAlign: "left",
            lineHeight: 1.1,
          },
          {
            id: "h-t3",
            type: "text",
            name: "Step 3 title",
            x: 1300,
            y: 360,
            width: 460,
            height: 80,
            opacity: 1,
            text: "Export",
            fontSize: 40,
            fontWeight: 700,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#f8fafc",
            textAlign: "left",
            lineHeight: 1.1,
          },
          {
            id: "h-d1",
            type: "text",
            name: "Step 1 body",
            x: 160,
            y: 460,
            width: 460,
            height: 360,
            opacity: 1,
            text: "Text, image, or container from the left rail. Click the slide to drop it. Double-click copy to edit.",
            fontSize: 26,
            fontWeight: 400,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#334155",
            textAlign: "left",
            lineHeight: 1.4,
          },
          {
            id: "h-d2",
            type: "text",
            name: "Step 2 body",
            x: 730,
            y: 460,
            width: 460,
            height: 360,
            opacity: 1,
            text: "Drag to move. Handles to resize. Arrow keys nudge. ⌘Z undoes. Layers stay on the left.",
            fontSize: 26,
            fontWeight: 400,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#334155",
            textAlign: "left",
            lineHeight: 1.4,
          },
          {
            id: "h-d3",
            type: "text",
            name: "Step 3 body",
            x: 1300,
            y: 460,
            width: 460,
            height: 360,
            opacity: 1,
            text: "Copy or download 16:9 HTML. The deck JSON rides along so the agent can load it back.",
            fontSize: 26,
            fontWeight: 400,
            fontFamily: "Inter, system-ui, sans-serif",
            color: "#cbd5e1",
            textAlign: "left",
            lineHeight: 1.4,
          },
        ],
      },
    ],
  };
}
